name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up --build

      - name: Wait for services
        run: |
          sleep 15

      - name: Tear down Docker Compose
        run: |
          docker compose down
