name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - name: Set up Docker Compose
      run: |
        docker compose up --build

    - name: Wait for services
      run: |
        sleep 15

    - name: Down
      run: |
        docker compose down